version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12-local-test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret